services:
  - type: web
    runtime: node
    name: version-tracker-server
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: FIREBASE_SERVICE_ACCOUNT_JSON
        sync: false
      - key: CRON_SCHEDULE
        value: "*/30 * * * *"
      - key: RENDER_URL
        sync: false
      - key: WHATSAPP_BOT_URL
        value: https://whatsapp-bot-m6bc.onrender.com
